name: Push Testing

on: [push]

jobs:
  Test-Commited-Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - run: npm ci
      - run: npm test
